/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.inikah.slayer.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Bridge service. Represents a row in the &quot;inikah_Bridge&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.inikah.slayer.model.impl.BridgeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.inikah.slayer.model.impl.BridgeImpl}.
 * </p>
 *
 * @author Ahmed Hasan
 * @see Bridge
 * @see com.inikah.slayer.model.impl.BridgeImpl
 * @see com.inikah.slayer.model.impl.BridgeModelImpl
 * @generated
 */
public interface BridgeModel extends BaseModel<Bridge> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bridge model instance should use the {@link Bridge} interface instead.
	 */

	/**
	 * Returns the primary key of this bridge.
	 *
	 * @return the primary key of this bridge
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bridge.
	 *
	 * @param primaryKey the primary key of this bridge
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rec ID of this bridge.
	 *
	 * @return the rec ID of this bridge
	 */
	public long getRecId();

	/**
	 * Sets the rec ID of this bridge.
	 *
	 * @param recId the rec ID of this bridge
	 */
	public void setRecId(long recId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Bridge bridge);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Bridge> toCacheModel();

	@Override
	public Bridge toEscapedModel();

	@Override
	public Bridge toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}