/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.inikah.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MMRegion service. Represents a row in the &quot;inikah_MMRegion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.inikah.slayer.model.impl.MMRegionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.inikah.slayer.model.impl.MMRegionImpl}.
 * </p>
 *
 * @author Ahmed Hasan
 * @see MMRegion
 * @see com.inikah.slayer.model.impl.MMRegionImpl
 * @see com.inikah.slayer.model.impl.MMRegionModelImpl
 * @generated
 */
public interface MMRegionModel extends BaseModel<MMRegion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a m m region model instance should use the {@link MMRegion} interface instead.
	 */

	/**
	 * Returns the primary key of this m m region.
	 *
	 * @return the primary key of this m m region
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this m m region.
	 *
	 * @param primaryKey the primary key of this m m region
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the region ID of this m m region.
	 *
	 * @return the region ID of this m m region
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this m m region.
	 *
	 * @param regionId the region ID of this m m region
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the country ID of this m m region.
	 *
	 * @return the country ID of this m m region
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this m m region.
	 *
	 * @param countryId the country ID of this m m region
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the iso code of this m m region.
	 *
	 * @return the iso code of this m m region
	 */
	@AutoEscape
	public String getIsoCode();

	/**
	 * Sets the iso code of this m m region.
	 *
	 * @param isoCode the iso code of this m m region
	 */
	public void setIsoCode(String isoCode);

	/**
	 * Returns the name of this m m region.
	 *
	 * @return the name of this m m region
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this m m region.
	 *
	 * @param name the name of this m m region
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MMRegion mmRegion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MMRegion> toCacheModel();

	@Override
	public MMRegion toEscapedModel();

	@Override
	public MMRegion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}